### ISSUE TITLE
Type stubs?

### ISSUE THREAD

**Issue by shayded-exe** [mido/mido#392] opened 2022-10-27 01:33 UTC
Functions like `mido.get_input_names` give the error `not a known member of module` with pylance in vscode.

**Comment by rdoursenaud** [comment] 2023-01-19 18:04
Somewhat related to #157

**Comment by rdoursenaud** [comment] 2023-07-20 02:19
Upon closer inspection it's definitely a duplicate of #157. I'll close your issue for now. Please track #157 for resolution.

**Closed by rdoursenaud** 2023-07-20 02:19 UTC
Labels: duplicate, enhancement, documentation
